// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "apps/chatbot-api/prisma/schema.prisma",
  migrations: {
    path: "apps/chatbot-api/prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? 'postgresql://postgres:mysecretpassword@localhost:5433/postgres?schema=public',
  },
});
